services:
  db:
    image: postgis/postgis:13-3.2-alpine
    restart: always
    environment:
      TZ: Europe/Paris
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: ghcr.io/mastergeonum/fukush-e-map:latest
    restart: always
    environment:
      - PGSERVICEFILE=/app/pg_service.conf
    volumes:
      - ./pg_service.conf:/app/pg_service.conf:ro

  front:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db-data: